### ISSUE TITLE
UndefInitializer -> cannot save as BSON / JLD

### ISSUE THREAD

**Issue by kafisatz** [JuliaData/SentinelArrays.jl#24]
A dataframe of mine has the type below.
It has four unique entries (three strings and missing) 
When trying to save this as BSON/JLD I get an UndeRefError.
Is there any way to keep working with SentinelArray and 'get rid of UndefInitializer'? 
Or is there an option for CSV.read to avoid this? 

I gather they are looking to make 'undef' work for BSON https://github.com/JuliaIO/BSON.jl/issues/43
Then again, my data has no undef. Only the type has 'undef'...

this works for me (for the time being) :
`dfraw.Instanz = convert(Array{Union{Missing,String},1},dfraw.Instanz);`

```
df.Instanz
125845-element SentinelArrays.SentinelArray{String,1,UndefInitializer,Missing,Array{String,1}}:

#when saving to BSON or JLD file I get this error
ERROR: UndefRefError: access to undefined reference
```

I also mentioned this here
https://github.com/JuliaIO/BSON.jl/issues/3#issuecomment-667908019

**Comment by kafisatz** [comment]
MWE
```
using DataFrames
using CSV
using BSON

df = DataFrame(a=[1,2],b=[missing,"mi"])
fi=mktemp()[1]
CSV.write(fi,df);
dfr = CSV.read(fi,DataFrame,pool=false);
@assert isa(dfr[2],CSV.SentinelArrays.SentinelArray{String,1,UndefInitializer,Missing,Array{String,1}})

isfile(fi)&&rm(fi)
BSON.@save fi dfr
```

**Comment by quinnj** [comment]
By default, any "reference" type will use `#undef` as the sentinel value underneath, so `SentinelArray([missing, "hey"])` will show that the array type is `Union{Missing, String}`, but it's actually using `#undef` under the hood to signal `missing`. Seems like you already found a work-around for the BSON.jl issue of not being able to handle `#undef`?

**Comment by kafisatz** [comment]
No. I do not have a workaround. 
More interestingly the error also happens when there are no missing entries. It seems the error is related to the column type rather than the occurrence of missing entries.

**Comment by quinnj** [comment]
Yes, that is interesting.

I was confused when you said:

> this works for me (for the time being) :
> dfraw.Instanz = convert(Array{Union{Missing,String},1},dfraw.Instanz);

does that not work as a workaround?

**Comment by kafisatz** [comment]
Yes it does work.
