### ISSUE TITLE
Copying/similar for SentinelArray

### ISSUE THREAD

**Issue by bkamins** [JuliaData/SentinelArrays.jl#34]
I propose that `copy`/`similar` etc. for `SentinelArray` should create a standard `Array`. The reason is that standard `Array` is faster so it is good to drop `SentinelArray` the moment it is not needed to be kept.

@quinnj - is there any value in keeping the type of `SentinelArray` here? (apart from being able to better catch Julia compiler problems like in https://github.com/JuliaData/DataFrames.jl/issues/2382 :smile:)

**Comment by bkamins** [comment]
@nalimilan - any opinion on this?

**Comment by nalimilan** [comment]
I agree that would make sense, provided that convert to `Array` isn't too slow compared to just copying the `SentinelArray` structure. That would make things simpler for users and be more likely to benefit from optimized methods designed for `Array`.

**Comment by bkamins** [comment]
The major problem is that `ChainedVector` is slow when doing random assess to it (at least this is what my testing shows - maybe @quinnj will disagree :smile:). Still I believe that we can make this conversion efficiently.
