### ISSUE TITLE
argmax for chained vector

### ISSUE THREAD

**Issue by bkamins** [JuliaData/SentinelArrays.jl#51]
@quinnj see the discussion in https://discourse.julialang.org/t/findmax-and-friends-confusing-behaviour-to-be-introduced-in-1-7/61904/79

I think the referenced definition should be fixed. Right?

**Comment by quinnj** [comment]
That thread is super long; can you give a TL;DR of what we need to change here?

**Comment by bkamins** [comment]
`argmax(f, A)` definition in SentinelArrays.jl is inconsistent with a newly added in 1.7 generic `argmax(f, A)` definition in Julia Base.

**Comment by quinnj** [comment]
Ah. What's the new definition? Is it hard to adjust what we currently have defined?

**Comment by bkamins** [comment]
No, it is simple:
```
  argmax(f, domain)

  Return a value x in the domain of f for which f(x) is maximised. If there are multiple maximal values for f(x) then
  the first one will be found.

  domain must be a non-empty iterable.

  Values are compared with isless.

  │ Julia 1.7
  │
  │  This method requires Julia 1.7 or later.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> argmax(abs, -10:5)
  -10

  julia> argmax(cos, 0:π/2:2π)
  0.0
```

As you can see the difference is that VALUE not INDEX should be returned.

**Comment by quinnj** [comment]
Sorry I forgot about this; PR here: https://github.com/JuliaData/SentinelArrays.jl/pull/59
