### ISSUE TITLE
`getindex` definition creates ambiguities 

### ISSUE THREAD

**Issue by jd-lara** [JuliaData/SentinelArrays.jl#56]
In `PowerSystems.jl` we have a dependency on CSV that uses `SentinelArrays.jl` and since we have also implemented a `getindex` method that works on an arbitrary set of indices, it is creating an ambiguity within our code

See the logs

https://github.com/NREL-SIIP/PowerSystems.jl/runs/3131816826

```Julia
1 ambiguities found
145
Ambiguity #1
146
getindex(A::AbstractArray, x::SentinelArrays.ChainedVectorIndex) in SentinelArrays at /home/runner/.julia/packages/SentinelArrays/GWZtM/src/chainedvector.jl:208
147
getindex(A::PowerSystems.PowerNetworkMatrix, idx...) in PowerSystems at /home/runner/work/PowerSystems.jl/PowerSystems.jl/src/utils/network_calculations/common.jl:91
```

Seems that #54 is the culprit of the issue.

**Comment by quinnj** [comment]
A new release was made yesterday w/ a fix (shortly after the release that introduced the ambiguity); let me know if you still see problems after upgrading
