### ISSUE TITLE
`push!` type piracy

### ISSUE THREAD

**Issue by adienes** [JuliaData/SentinelArrays.jl#94]
https://github.com/JuliaData/SentinelArrays.jl/blob/fa840f994ae821d921a9973fbd5e244d35102b1c/src/BufferedVectors.jl#L32

I think the piracy here should be avoided if possible. I noticed this when the error message for something like `push!(0, 0)` changed

**Comment by ancapdev** [comment]
I hit this today.  To type pirate an function as core as `Base.push!()` seems rather presumptuous.

**Comment by Drvi** [comment]
Ah I see what is going on, I'll make a PR shortly. Thanks all!
